###
POST http://127.0.0.1:9000/webhook/raw/ding HTTP/1.1
Content-Type: text/plain

"raw string send"

###
POST http://127.0.0.1:9000/webhook/raw/ding?secret=xxxxxxxxxxxxxxxxx HTTP/1.1
Content-Type: text/plain

"raw string send"

// https://support.huaweicloud.com/intl/en-us/usermanual-smn/smn_ug_a9002.html
###
POST http://127.0.0.1:9000/webhook/huaweismn/ding HTTP/1.1
Content-Type: application/json

< ./huaweismn-notification.json

###
POST http://127.0.0.1:9000/webhook/huaweismn/ding HTTP/1.1
content-type: application/json

< ./huaweismn-subscription.json


// https://www.puppeteers.net/blog/testing-alertmanager-webhooks-with-curl/
###
POST http://127.0.0.1:9000/webhook/prom/ding HTTP/1.1
content-type: application/json

< ./prom-notification.json

###
POST http://127.0.0.1:9000/webhook/prom/ding HTTP/1.1
content-type: application/json

< ./huaweismn-notification-temp.json

