apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-webhook-receiver
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: alert-webhook-receiver
  template:
    metadata:
      labels:
        app: alert-webhook-receiver
    spec:
      containers:
        - name: alert-webhook-receiver
          image: xianleeti/alert-webhook-receiver:v0.1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: DING_ROBOT_TOKEN
              value: xxxxxxxxxxxxxxxxxxxxxxxxxxx
            - name: DING_ROBOT_SECRET
              value: SECxxxxxxxxxxxxxxxxxxxxxxxxxxx
            - name: WEBHOOK_SECRET_KEY
              value: asdfasdfasdfasdfasdf
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: alert-webhook-receiver
  namespace: monitoring
spec:
  selector:
    app: alert-webhook-receiver
  ports:
    - name: hook
      port: 9000
      targetPort: http
  # type: NodePort
